# Setup
title:               Puzzles
tagline:             'by Jeff Davidson'
description:         'Mostly mini variety word puzzles by <a href="https://twitter.com/jpdavidson" target="_blank">@jpdavidson</a>.'
url:                 https://puzzles.jeffpdavidson.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jeff Davidson
  url:               https://twitter.com/jpdavidson

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y

webrick:
  headers:
    Access-Control-Allow-Origin: "*"
